# Generated by Django 5.2 on 2025-04-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0003_property_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
